shoki/models.py
from shoki import db, bcrypt
from datetime import datetime

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20),unique=True,nullable=False)
    email = db.Column(db.String(120),nullable=False)
    hash_password = db.Column(db.String(60),nullable=False)
    rsis = db.relationship('Rsi', backref='user', lazy=True)
    
    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.hash_password = bcrypt.generate_password_hash(password)
        
    def __repr__(self):
        return f"User({self.username},{self.email},{self.hash_password})"
    
    def check_password(self, password):
        return bcrypt.check_password_hash(self.hash_password, password)
    
class Rsi(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    project_name = db.Column(db.String(20),nullable=False)
    site_name = db.Column(db.String(20),nullable=False)
    direction = db.Column(db.String(30),nullable=False)
    vehicle_type = db.Column(db.String(30),nullable=False)
    addr1_og = db.Column(db.String(30),nullable=True)
    addr2_og = db.Column(db.String(30),nullable=True)
    addr3_og = db.Column(db.String(30),nullable=True)
    zone_og = db.Column(db.Integer,nullable=False)
    addr1_dn = db.Column(db.String(30),nullable=True)
    addr2_dn = db.Column(db.String(30),nullable=True)
    addr3_dn = db.Column(db.String(30),nullable=True)
    zone_dn = db.Column(db.Integer,nullable=False)
    trip_purpose = db.Column(db.String(30),nullable=False)
    passenger12 = db.Column(db.Integer,nullable=True)
    passenger34 = db.Column(db.String(30),nullable=True)
    passenger58 = db.Column(db.Integer,nullable=True)
    cargo_type = db.Column(db.String(30),nullable=True)
    cargo_weight = db.Column(db.String(30),nullable=True)
    income = db.Column(db.String(30),nullable=False)
    surveyor_name = db.Column(db.String(20),nullable=False)
    crated_at = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)
    
    
    

shoki/__init__.py
import os
from flask import Flask
from flask_bcrypt import Bcrypt
import secrets
from datetime import timedelta
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
     
app = Flask(__name__)
# set base Directory
basedir = os.path.abspath(os.path.dirname(__file__))
# create the secret_key_hash
secret_key = secrets.token_hex(16)
bcrypt = Bcrypt(app)
secret_key_hash = bcrypt.generate_password_hash(secret_key)
# Database configuration
app.config['SECRET_KEY'] = secret_key_hash
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.permanent_session_lifetime = timedelta(minutes=45)
# build database
db = SQLAlchemy(app)
Migrate(app,db)

from .views import views
from .auth import auth
from .rsi import rsi

# create the Views Blueprint
app.register_blueprint(views, url_prefix='/')
app.register_blueprint(auth, url_prefix='/')
app.register_blueprint(rsi, url_prefix='/')


    

shoki/auth.py
from flask import Blueprint, render_template, url_for, redirect, session, flash, request
from shoki import db
from .models import User

auth = Blueprint("auth",__name__)

@auth.route('/adduser', methods=['GET','POST'])
def adduser():
    
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password_1']
        con_password = request.form['password_2']
        
        if len(username)<2:
            flash("ชื่อผู้ใช้ควรมีมากกว่า 2 ตัวอักษร กรุณากรอกอีกครั้ง!!!", "danger")

        elif len(email)<7:
            flash("อีเมลล์ไม่ถูกต้อง กรุณากรอกอีกครั้ง!!!", "danger")
        
        elif password != con_password:
            flash("รหัสผ่านไม่ตรงกัน กรุณากรองอีกครั้ง!!!", "danger")
            
        else:
            user = User.query.filter_by(email=email).first()
            if user:
                flash('อีเมลล์นี้มีการใช้งานในแอพลิเคชันแล้ว กรุณาเปลี่ยนอีเมลล์','danger')
                return redirect(url_for('views.signup'))
            user = User(username=username,email=email,password=password)
            db.session.add(user)
            db.session.commit()
            flash('ขอบคุณที่ลงทะเบียนเข้าใช้', 'success')
            return redirect(url_for('views.home'))
            
    return redirect(url_for('views.signup'))

@auth.route('/login', methods=['GET', 'POST'])
def login():
    
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        
        user = User.query.filter_by(email=email).first()
        
        if user is not None:
            if user.check_password(password):
                session['username'] = user.username
                session['id'] = user.id
                session.permanent = True
                flash('ยินดีต้อนรับสู่แอพลิเคชั่น','success')
                return redirect(url_for('rsi.showform'))
            else:
                flash('รหัสไม่ถูกต้อง โปรดลองอีกครั้ง','danger')
        else:       
            flash('อีเมลล์ไม่ถูกต้องหรือไม่คุณยังไม่ได้ลงทะเบียนเข้าใช้','danger')
        
    return render_template('home.html')

@auth.route('/logoff')
def logoff():
    session.clear()
    flash('คุณได้ออกจากแอพลิเคชั่นแล้ว ขอบคุณที่ใช้บริการ', 'success')    
    return redirect(url_for('views.home'))

shoki/views.py
from flask import Blueprint, render_template, url_for, redirect


views = Blueprint("views",__name__)

@views.route("/")
@views.route("/home")
def home():
    return render_template('home.html', name="HOME")

@views.route("/signup")
def signup():
    return render_template('signup.html', name="SIGNUP")

@views.route("/about")
def about():
    return render_template('about.html', name="ABOUT")

shoki/templates/about.html
{% extends "dashboard.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}
<section>
    <div class="contain text-center p-4">
        <h1 class="fw-bold" style="font-size: 30px;">SHOKI-RSI</h1>
        <h3 class="fw-bold" style="font-size: 25px;">v.1.00.1</h3>
    </div>
    <p class="lead text-center m-4">
        เป็นโปรแกรมประยุกต์ทำงานบนเว็บสำหรับสำรวจข้อมูลปริมาณการเดินทางริมถนน (Roadside Interview Survey)
        ซึ่งสามารถทำงานได้หลากหลายอุปกรณ์และสามารถนำไปปฎิบัติงานในจุดสำรวจได้ด้วยอุปกรณ์ที่เชื่อมต่อกับอินเตอร์เน็ตผ่านโปรแกรม
        web browser โปรแกรมประกอบด้วย 3 โมดูล ประกอบด้วย โมดูลฟอร์มการบันทึกข้อมูล โมดูลตารางข้อมูลจากการสำรวจ และ
        โมดูลการวิเคราะห์ข้อมูลการสำรวจ
    </p>

</section>

<section>
    <div class="container-fluid">
        <h3 class="text-center" style="font-size: 25px;">ผู้วิจัยและพัฒนา</h3>
    </div>
    <br>
    <div class="container-fluid">
        <div>
            <div class="card bg-light">
              <div class="card-body text-center">
                <img
                  src="{{ url_for('static', filename='img/IMG_71732.jpeg') }}"
                  class="rounded-circle mb-3 img-fluid"
                  width="130" height="130"
                />
                <h3 class="card-title mb-3">ณัฐวุธ กองสุทธิ</h3>
                <p class="card-text">
                  นักวางแผนด้านการขนส่ง และโปรแกรมเมอร์
                </p>
                <a href="https://twitter.com/a0271321"><i class="bi bi-twitter text-dark mx-1"></i></a>
                <a href="https://facebook.com/nkongsutthi"><i class="bi bi-facebook text-dark mx-1"></i></a>
                <a href="https://instagram.com/jornattawut"><i class="bi bi-instagram text-dark mx-1"></i></a>
              </div>
            </div>
        </div>
    </div>

</section>


{% endblock %}

shoki/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}"> 
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>{% block title%}{%endblock%}</title>
</head>
<body>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, msg in messages %}

                {% if category == 'danger' %}

                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>เกิดความผิดพลาด!</strong> {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>ประสบความสำเร็จ!</strong> {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

                {% endif %}

            {% endfor %}
        {% endif %}
    {% endwith %}

    {% block content%}{% endblock%}
    
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script> 
</body>
</html>

shoki/templates/dash.html
{% extends "base.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}

    <h1>Hello JOR</h1>

{% endblock %}

shoki/templates/dash_analysis.html
{% extends "dashboard.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}
<div class="contaner mt-5 p-3">
    <h1 class="text-center fw-bold" style="font-size: 30px;"><strong>การวิเคราะห์ข้อมูลการสำรวจปริมาณการเดินทางริมถนน</strong></h1>
    <p class="text-center fw-bold" style="font-size: 25px;"><strong>Roadside Interview Survey Analysis</strong></p>
    <br>
    <br>
    <form action="{{ url_for('rsi.visualization') }}" method="post">
        <div class="form-row">
            <div class="col">
              <label class="fw-bold" style="font-size: 20px;"><strong>รหัสโครงการ</strong></label>
              <input type="name" name="project_name" class="form-control" placeholder="รหัสโครงการ" required>
            </div>
            <br>
            <div class="col">
              <label class="fw-bold" style="font-size: 20px;"><strong>ชื่อจุดสำรวจ</strong></label>
              <input type="name" name="site_name" class="form-control" placeholder="ชื่อจุดสำรวจ" value='All' required>
            </div>
        </div>
        <br>
        <div>
            <button id="submit" type="submit" class="btn btn-secondary" style="float:right">Submit</button>
        </div>

    </form>

</div>


{% endblock %}

shoki/templates/dash_table.html
{% extends "dashboard.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}

    <div class="container mt-5 p-3">
        <h1 class="text-center fw-bold" style="font-size: 30px;"><strong>ตารางข้อมูลการสำรวจปริมาณการเดินทางริมถนน</strong></h1>
        <p class="text-center fw-bold" style="font-size: 25px;"><strong>Roadside Interview Survey Table</strong></p>
        <br>
        <br>
        <div class="table-responsive">
            <table class="table table-primary table-striped mb-0">
                <thead class="fw-bold">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">รหัสโครงการ</th>
                      <th scope="col">ชื่อจุดสำรวจ</th>
                      <th scope="col">ทิศทางการจราจร</th>
                      <th scope="col">ประเภทยานพาหนะ</th>
                      <th scope="col">ตำบลจุดเริ่มต้น</th>
                      <th scope="col">อำเภอจุดเริ่มต้น</th>
                      <th scope="col">จังหวัดจุดเริ่มต้น</th>
                      <th scope="col">รหัสพื้นที่จุดเริ่มต้น</th>
                      <th scope="col">ตำบลจุดปลายทาง</th>
                      <th scope="col">อำเภอจุดปลายทาง</th>
                      <th scope="col">จังหวัดจุดปลายทาง</th>
                      <th scope="col">รหัสพื้นที่จุดปลายทาง</th>
                      <th scope="col">วัตถุประสงค์การเดินทาง</th>
                      <th scope="col">จำนวนผู้โดยสาร(1&2)</th>
                      <th scope="col">จำนวนผู้โดยสาร(3&4)</th>
                      <th scope="col">จำนวนผู้โดยสาร(5,6,7&8)</th>
                      <th scope="col">ชนิดสินค้า</th>
                      <th scope="col">น้ำหนักสินค้า</th>
                      <th scope="col">ระดับรายได้</th>
                      <th scope="col">เวลาบันทึกข้อมูล</th>
                      <th scope="col">การกระทำข้อมูล</th>
                    </tr>
                </thead>
                <tbody>
                    {% for rsi in rsis.items %}
                    <tr>
                        <td>{{ rsi.id }}</td>
                        <td>{{ rsi.project_name }}</td>
                        <td>{{ rsi.site_name }}</td>
                        <td>{{ rsi.direction }}</td>
                        <td>{{ rsi.vehicle_type }}</td>
                        <td>{{ rsi.addr1_og }}</td>
                        <td>{{ rsi.addr2_og }}</td>
                        <td>{{ rsi.addr3_og }}</td>
                        <td>{{ rsi.zone_og }}</td>
                        <td>{{ rsi.addr1_dn }}</td>
                        <td>{{ rsi.addr2_dn }}</td>
                        <td>{{ rsi.addr3_dn }}</td>
                        <td>{{ rsi.zone_dn }}</td>
                        <td>{{ rsi.trip_purpose }}</td>
                        <td>{{ rsi.passenger12 }}</td>
                        <td>{{ rsi.passenger34 }}</td>
                        <td>{{ rsi.passenger58 }}</td>
                        <td>{{ rsi.cargo_type }}</td>
                        <td>{{ rsi.cargo_weight }}</td>
                        <td>{{ rsi.income }}</td>
                        <td>{{ rsi.crated_at }}</td>
                        <td class="table-action">
                            <a href="{{ url_for('rsi.updatersi', id=rsi.id) }}" class="btn btn-success">แก้ไข</a>
                            <a href= "{{ url_for('rsi.deletersi', id=rsi.id) }}" class="btn btn-danger">ลบ</a>
                        </td>

                    </tr>

                    {% endfor %}
                </tbody>

            </table>

        </div>
        <br>
        <div class="container">
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                  <li class="page-item {% if rsis.page == 1 %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('rsi.showtable', page=rsis.prev_num) }}" tabindex="-1" aria-disabled="true">ก่อนหน้า</a>
                  </li>
                  {% for page_num in rsis.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                        {% if page_num %}
                            {% if rsis.page == page_num %}
                                <li class="page-item active"><a class="page-link" href="{{ url_for('rsi.showtable', page=prev_num) }}">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="{{ url_for('rsi.showtable', page=prev_num) }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% else %}
                            ...
                        {% endif %}
                  {% endfor %}
                  <li class="page-item {% if rsis.page == rsis.pages %}disabled{% endif %}">
                    <a class="page-link" href="{{ url_for('rsi.showtable', page=rsis.next_num) }}">ถัดไป</a>
                  </li>
                </ul>

                <p class="text-center mt-3">แสดงหน้าที่ {{ rsis.page }} จากจำนวนหน้าทั้งหมด {{ rsis.pages }} หน้า</p>
            </nav>

        </div>

    </div>

{% endblock %}

shoki/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}"> 
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <title>{% block title%}{%endblock%}</title>
</head>
<body>

    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, msg in messages %}

                {% if category == 'danger' %}

                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>เกิดความผิดพลาด!</strong> {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>ประสบความสำเร็จ!</strong> {{ msg }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

                {% endif %}

            {% endfor %}
        {% endif %}
    {% endwith %}

    

    <header class="p-3 mb-3 border-bottom">
        <div class="container" style="font-size:20px;">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <span class="fs-4">SHOKI-RSI</span>
            </a>
    
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              {% if name == 'FORM' %}
                  <li><a href="{{ url_for('rsi.showform') }}" class="nav-link px-2 link-secondary">แบบสำรวจ</a></li>
              {% else %}
                  <li><a href="{{ url_for('rsi.showform') }}" class="nav-link px-2 link-dark">แบบสำรวจ</a></li>
              {% endif %}
              {% if name == 'TABLE' %}
                  <li><a href="{{ url_for('rsi.showtable') }}" class="nav-link px-2 link-secondary">ตารางข้อมูล</a></li>
              {% else %}
                  <li><a href="{{ url_for('rsi.showtable') }}" class="nav-link px-2 link-dark">ตารางข้อมูล</a></li>
              {% endif %}
              {% if name == 'ANALYSIS' %}
              <li><a href="{{ url_for('rsi.showanalysis') }}" class="nav-link px-2 link-secondary">การวิเคราะห์ข้อมูล</a></li>
              {% else %}
              <li><a href="{{ url_for('rsi.showanalysis') }}" class="nav-link px-2 link-dark">การวิเคราะห์ข้อมูล</a></li>
              {% endif %}
              {% if name == 'ABOUT' %}
              <li><a href="{{ url_for('views.about') }}" class="nav-link px-2 link-secondary">เกี่ยวกับเรา</a></li>
              {% else %}
              <li><a href="{{ url_for('views.about') }}" class="nav-link px-2 link-dark">เกี่ยวกับเรา</a></li>
              {% endif %}
            </ul>
    
            {% if name == 'TABLE' %}
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{{ url_for('rsi.search') }}" method=post>
              <input type="search" class="form-control" placeholder="ค้นหา..." aria-label="Search" name ="search" value="{{ request.form.search }}">
              <!-- <button type="submit" class="btn btn-secondary" >ค้นหา</button> -->
            </form>
            {% endif %}
    
            <div class="dropdown text-end">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="fs-4">{{ session['username'] }}</span>
              </a>
              <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="#">ข้อมูลส่วนตัว</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{{ url_for('auth.logoff') }}">ออกจากระบบ</a></li>
              </ul>
            </div>
          </div>
        </div>
    </header>

    {% block content%}{% endblock%}
    
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script> 
</body>
</html>

shoki/templates/home.html
{% extends "base.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}

<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">โปรแกรมแบบสอบถามการสำรวจปริมาณการเดินทางริมถนน (Roadside Interview Survey Application)</h1>
        <p class="col-lg-10 fs-4 m-3">
            เป็นโปรแกรมประยุกต์ทำงานบนเว็บสำหรับช่วยให้ผู้สำรวจปริมาณการเดินทางริมถนนสามารถสำรวจข้อมูล จัดเก็บข้อมูลและวิเคราะห์ข้อมูลได้อย่างรวดเร็วและมีประสิทธิภาพ
        </p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form action="{{ url_for('auth.login') }}" method="post" class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" name='email' placeholder="name@example.com" required>
            <label for="floatingInput">อีเมลล์</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" name='password' placeholder="Password" required>
            <label for="floatingPassword">รหัสผ่าน</label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">เข้าใช้งาน</button>
          <hr class="my-4">
          <small class="text-muted" style="font-size:12;">โปรด<a href="{{ url_for('views.signup') }}">ลงทะเบียนเข้าใช้</a> ถ้าคุณยังไม่ได้เป็นสมาชิก!!!</small>
        </form>
      </div>
    </div>
</div>

{% endblock %}

shoki/templates/signup.html
{% extends "base.html" %}
{% block title%}{{ name }}{% endblock %}

{% block content %}

<main class="form-signup">
  <div class="contrainer text-center">
    <form action="{{ url_for('auth.adduser') }}" method="post" class="p-4 p-md-5 border rounded-3 bg-light" >

      <h1 class="h1 mb-3 fw-bold mt-5">โปรดลงทะเบียน</h1>
  
      <div class="form-floating">
        <input type="text" class="form-control" id="floatingInput" name="username" placeholder="ชื่อผู้ใช้งาน" required/>
        <label for="floatingInput">ชื่อผู้ใช้งาน</label>
      </div>
      <div class="form-floating">
        <input type="email" class="form-control" id="floatingInput" name="email" placeholder="อีเมลล์" required/>
        <label for="floatingInput">อีเมลล์</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" name="password_1" placeholder="รหัสผ่าน" required/>
        <label for="floatingPassword">รหัสผ่าน</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" name="password_2" placeholder="ยืนยันรหัสผ่าน" required/>
        <label for="floatingPassword">ยืนยันรหัสผ่าน</label>
      </div>
  
      <br>
      <button class="w-100 btn btn-lg btn-primary" type="submit">ลงทะเบียน</button>
      <p class="mt-5 mb-3 text-muted">SHOKI &copy; 2022</p>
    </form>
  </div>
    
</main>

{% endblock %}